name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - id: Checkout
        uses: actions/checkout@v6
      - id: "Setup node"
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - id: "Install bats"
        run: npm install -g bats
      - id: "Check bats version"
        run: bats -v
